# Generated by Django 4.2.3 on 2023-10-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_expensebyemployee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseByEmployee',
        ),
    ]
